### ISSUE TITLE
A thing

### ISSUE THREAD

**Issue by popdynamite5511** [hdfsyu/2DMinecraft#1]
**MacOS**
I think you know what I'm talking about

**Comment by hdfsyu** [comment]
?

**Comment by popdynamite5511** [comment]
it doesnt work on macos

**Comment by hdfsyu** [comment]
...
use the web version

**Comment by popdynamite5511** [comment]
yes however this bug report is not about the web version
if the jar version does not work for mac, why even put it in the releasess

**Comment by hdfsyu** [comment]
solution: web version
and i didnt even intend for it to be supported on macOS @popdynamite5511

**Comment by hdfsyu** [comment]
thats why i made the web version in the first place!

**Comment by popdynamite5511** [comment]
then don't say that it works for all platforms (you said that in the release)
